In [1]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import plotly.express as px
import scipy.stats as stats

mpl.rc('font', family='Malgun Gothic')

In [2]:
df1= pd.read_csv('preprocessing_data.csv')

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 752 entries, 0 to 751
Data columns (total 60 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           752 non-null    int64
 1   Ox_Chamber           752 non-null    int64
 2   process              752 non-null    object
 3   type                 752 non-null    object
 4   Temp_OXid            752 non-null    float64
 5   Vapor                752 non-null    object
 6   ppm                  752 non-null    float64
 7   Pressure             752 non-null    float64
 8   Oxid_time            752 non-null    float64
 9   thickness            752 non-null    float64
 10  No_Die               752 non-null    object
 11  Reinforcement        752 non-null    bool
 12  Unnamed: 0_x         752 non-null    int64
 13  photo_soft_Chamber   752 non-null    int64
 14  process 2            752 non-null    object
 15  resist_target        752 non-null    float64
 16  N2_HMDS              752 non-null    float64
 17  pressure_HMDS        752 non-null    float64
 18  temp_HMDS            752 non-null    float64
 19  temp_HMDS_bake       752 non-null    float64
 20  time_HMDS_bake       752 non-null    float64
 21  spin1                752 non-null    float64
 22  spin2                752 non-null    float64
 23  spin3                752 non-null    float64
 24  photoresist_bake     752 non-null    float64
 25  temp_softbake        752 non-null    float64
 26  time_softbake        752 non-null    float64
 27  lithography_Chamber  752 non-null    int64
 28  Line_CD              752 non-null    float64
 29  UV_type              752 non-null    object
 30  Wavelength           752 non-null    int64
 31  Resolution           752 non-null    float64
 32  Energy_Exposure      752 non-null    float64
 33  Range_check          752 non-null    bool
 34  Unnamed: 0_y         752 non-null    int64
 35  Etching_Chamber      752 non-null    int64
 36  Process 3            752 non-null    object
 37  Temp_Etching         752 non-null    float64
 38  Source_Power         752 non-null    float64
 39  Selectivity          752 non-null    float64
 40  Thin Film 4          752 non-null    float64
 41  Thin Film 3          752 non-null    float64
 42  Thin Film 2          752 non-null    float64
 43  Thin Film 1          752 non-null    float64
 44  Etching_rate         752 non-null    float64
 45  Chamber_Num          752 non-null    int64
 46  process4             752 non-null    object
 47  Flux60s              752 non-null    float64
 48  Flux90s              752 non-null    float64
 49  Flux160s             752 non-null    float64
 50  Flux480s             752 non-null    float64
 51  Flux840s             752 non-null    float64
 52  input_Energy         752 non-null    float64
 53  Temp_implantation    752 non-null    float64
 54  Furance_Temp         752 non-null    float64
 55  RTA_Temp             752 non-null    int64
 56  Target               752 non-null    int64
 57  Error_message        752 non-null    object
 58  target_binom         752 non-null    float64
 59  Chamber_Route        752 non-null    object
dtypes: bool(2), float64(37), int64(11), object(10)
memory usage: 342.3+ KB

In [3]:
# 회귀 모형 평가
Y = df1['Target']  # Wafer 내 불량 Chip 개수
X = df1[['Temp_OXid', 'Oxid_time', 'thickness', 'Line_CD', 'Etching_rate', 'Temp_Etching']]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=1234)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(564, 6)
(188, 6)
(564,)
(188,)

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [8]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [9]:
# 함수형태로 회귀모형 검사하는 시스템 만들기
def evaluation_reg(model) : 
    Y_train_pred = model.predict(X_train)
    Y_test_pred = model.predict(X_test)
    print('학습 데이터 결정계수 : ', r2_score(Y_train, Y_train_pred))
    print('검증 데이터 결정계수 : ', r2_score(Y_test, Y_test_pred))
    print('학습 데이터 MSE: ', mean_squared_error(Y_train, Y_train_pred))
    print('검증 데이터 MSE: ', mean_squared_error(Y_test, Y_test_pred))
    print('학습 데이터 MAE: ', mean_absolute_error(Y_train, Y_train_pred))
    print('검증 데이터 MAE: ', mean_absolute_error(Y_test, Y_test_pred))

In [10]:
evaluation_reg(model)

학습 데이터 결정계수 :  0.3458237902299178
검증 데이터 결정계수 :  0.2939680114254164
학습 데이터 MSE:  2684.9553213362346
검증 데이터 MSE:  2089.4785779224812
학습 데이터 MAE:  37.23001161802481
검증 데이터 MAE:  34.71724975119027

In [11]:
Y_train_pred = model.predict(X_train)
Y_test_pred = model.predict(X_test)

In [12]:
r2_score(Y_train, Y_train_pred)

0.3458237902299178

In [13]:
r2_score(Y_test, Y_test_pred)

0.2939680114254164

In [14]:
mean_squared_error(Y_train, Y_train_pred)

2684.9553213362346

In [15]:
mean_squared_error(Y_test, Y_test_pred)

2089.4785779224812

# 특성 공학 기법 적용

- Pipe Line : 학습과 특성공학 기법을 동시에 사용하여, 데이터를 한꺼번에 처리하면서 학습을 수행하는 함수

In [16]:
from sklearn.pipeline import Pipeline  # 학습 + 특성공학 
from sklearn.impute import SimpleImputer  # 결측값 처리 함수 (단순 처리)

In [17]:
pipe_list = [( 'imputer',SimpleImputer() ),
             ( 'model', LinearRegression()) ]    # -> 리스트 안에 튜플 구조로 처리 
pipe_model = Pipeline(pipe_list)
pipe_model            # steps : 데이터의 서열 순서(처리 순서)를 보여줌 / 결측치가 처리 되고 학습이 수행되는 구조

Pipeline(steps=[('imputer', SimpleImputer()), ('model', LinearRegression())])

In [18]:
pipe_model.fit(X_train, Y_train)

Pipeline(steps=[('imputer', SimpleImputer()), ('model', LinearRegression())])

In [19]:
evaluation_reg(pipe_model)

학습 데이터 결정계수 :  0.3458237902299178
검증 데이터 결정계수 :  0.2939680114254164
학습 데이터 MSE:  2684.9553213362346
검증 데이터 MSE:  2089.4785779224812
학습 데이터 MAE:  37.23001161802481
검증 데이터 MAE:  34.71724975119027

**새로운 값을 직접 입력하여 예측 **

In [20]:
X1 = input('Temp_0xid 을 입력하시오 : ')
X2 = input('Oxid_time 을 입력하시오 : ')
X3 = input('thickness 입력하시오 : ')
X4 = input('Line_CD 입력하시오 : ')
X5 = input('Etching_rate 입력하시오 : ')
X6 = input('Temp_Etching 입력하시오 : ')

Temp_0xid 을 입력하시오 : 100
Oxid_time 을 입력하시오 : 200
thickness 입력하시오 : 100
Line_CD 입력하시오 : 50
Etching_rate 입력하시오 : 100
Temp_Etching 입력하시오 : 100

In [21]:
input_new_data =pd.DataFrame([[X1, X2, X3, X4, X5, X6]])

In [22]:
pipe_model.predict(input_new_data)

E:\aaan\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

array([117528.77500824])

** 결측값이 있어도, 위에 설계한 Pipe Line 함수로 인해 오류 없이 예측값이 계산되어 출력 된다**

In [23]:
import numpy as np

In [24]:
input_new_data2 = pd.DataFrame([[X1, np.nan, X3, X4, X5, X6]], columns=X.columns.tolist())
input_new_data2

  Temp_OXid  Oxid_time thickness Line_CD Etching_rate Temp_Etching
0       100        NaN       100      50          100          100

In [25]:
pipe_model.predict(input_new_data)

E:\aaan\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

array([117528.77500824])

**Scaling & Encoding**

- Scaling -> 연속형
- Encoding -> 범주형 
- Imputation -> 연속 / 범주 
- 결론 : 숫자 데이터냐 문자 데이터에 따라 전처리가 달라진다

In [26]:
df1.columns

Index(['Unnamed: 0', 'Ox_Chamber', 'process', 'type', 'Temp_OXid', 'Vapor',
       'ppm', 'Pressure', 'Oxid_time', 'thickness', 'No_Die', 'Reinforcement',
       'Unnamed: 0_x', 'photo_soft_Chamber', 'process 2', 'resist_target',
       'N2_HMDS', 'pressure_HMDS', 'temp_HMDS', 'temp_HMDS_bake',
       'time_HMDS_bake', 'spin1', 'spin2', 'spin3', 'photoresist_bake',
       'temp_softbake', 'time_softbake', 'lithography_Chamber', 'Line_CD',
       'UV_type', 'Wavelength', 'Resolution', 'Energy_Exposure', 'Range_check',
       'Unnamed: 0_y', 'Etching_Chamber', 'Process 3', 'Temp_Etching',
       'Source_Power', 'Selectivity', 'Thin Film 4', 'Thin Film 3',
       'Thin Film 2', 'Thin Film 1', 'Etching_rate', 'Chamber_Num', 'process4',
       'Flux60s', 'Flux90s', 'Flux160s', 'Flux480s', 'Flux840s',
       'input_Energy', 'Temp_implantation', 'Furance_Temp', 'RTA_Temp',
       'Target', 'Error_message', 'target_binom', 'Chamber_Route'],
      dtype='object')

In [27]:
Y = df1['Target']
X = df1[['Oxid_time', 'thickness', 'Vapor', 'resist_target', 'Line_CD', 'Etching_rate', 'UV_type' ]]

In [28]:
X

     Oxid_time  thickness Vapor  resist_target  Line_CD  Etching_rate UV_type
0         62.0    699.443    O2       1.211940   30.959       2.75950       H
1        137.0    696.792    O2       0.887720   29.653       2.72775       H
2        128.0    705.471    O2       1.113156   28.063       2.67000       I
3         90.0    710.772    O2       0.882195   31.556       2.74825       I
4         98.0    716.975    O2       0.834001   31.969       2.74625       I
..         ...        ...   ...            ...      ...           ...     ...
747       21.0    708.586   H2O       0.923802   35.404       2.67450       I
748       22.0    712.936   H2O       0.837348   31.011       2.72725       I
749       21.0    715.498   H2O       0.859869   32.525       2.72275       I
750       22.0    707.179   H2O       0.914315   28.001       2.69150       I
751       22.0    716.238   H2O       0.938200   30.007       2.70525       I

[752 rows x 7 columns]

In [29]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=1234)

In [30]:
# 문자데이터와 숫자데이터를 구분하여 처리하는 프로세스를 구축할 때 사용하는 함수 
from sklearn.compose  import make_column_transformer
# 특성공학 + 학습
from sklearn.pipeline import make_pipeline
# Scaling & Encoding 
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

In [31]:
# 연속형/범주형 데이터 항목명을 리스트로 선언 
numeric_list = ['Oxid_time', 'thickness', 'resist_target', 'Line_CD', 'Etching_rate']
category_list = ['Vapor', 'UV_type']

In [32]:
# 연속형 데이터가 처리되는 Process
# 결측값을 평균으로 대치한 다음, Scale을 최소 0 / 최대 1으로 변환 
numeric_pipe = make_pipeline( SimpleImputer(strategy='mean'), MinMaxScaler())
numeric_pipe

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('minmaxscaler', MinMaxScaler())])

In [33]:
# 범주형 데이터가 처리되는 Process 
# 결측값을 최빈값으로 대치한 다음, 문자데이터를 OneHotEucoding 으로 변환 
category_pipe = make_pipeline( SimpleImputer(strategy='most_frequent'), OneHotEncoder())
category_pipe

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                ('onehotencoder', OneHotEncoder())])

In [34]:
# 연속형과 범주형을 나누어 처리하는 pipe를 구성 
preprocessing_pipe = make_column_transformer( (numeric_pipe, numeric_list), (category_pipe, category_list) )
preprocessing_pipe

ColumnTransformer(transformers=[('pipeline-1',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer()),
                                                 ('minmaxscaler',
                                                  MinMaxScaler())]),
                                 ['Oxid_time', 'thickness', 'resist_target',
                                  'Line_CD', 'Etching_rate']),
                                ('pipeline-2',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder())]),
                                 ['Vapor', 'UV_type'])])

In [35]:
pipe_model = make_pipeline(preprocessing_pipe, LinearRegression() )

In [36]:
pipe_model

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer()),
                                                                  ('minmaxscaler',
                                                                   MinMaxScaler())]),
                                                  ['Oxid_time', 'thickness',
                                                   'resist_target', 'Line_CD',
                                                   'Etching_rate']),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder())]),
                                                  ['Vapor', 'UV_type'])])),
                ('linearregression', LinearRegression())])

In [37]:
pipe_model.fit(X_train, Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer()),
                                                                  ('minmaxscaler',
                                                                   MinMaxScaler())]),
                                                  ['Oxid_time', 'thickness',
                                                   'resist_target', 'Line_CD',
                                                   'Etching_rate']),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder())]),
                                                  ['Vapor', 'UV_type'])])),
                ('linearregression', LinearRegression())])

In [38]:
evaluation_reg(pipe_model)

학습 데이터 결정계수 :  0.38311464373728366
검증 데이터 결정계수 :  0.28547901254699726
학습 데이터 MSE:  2531.901336696589
검증 데이터 MSE:  2114.6014924525657
학습 데이터 MAE:  36.33614506435797
검증 데이터 MAE:  35.58755076958039

**교차 검증 Cross Validation (CV)**

In [39]:
from sklearn.model_selection import GridSearchCV

In [40]:
# 5회의 교차검증을 실시하며 학습을 수행 (pipe Model의 Process를 따라가며 학습)
grid_model = GridSearchCV(pipe_model, param_grid={ }, cv=5)
grid_model.fit(X_train, Y_train) # -> 이걸 하면 위에 "pipe_model.fit(X_train, Y_train)"을 쓸 필요 없이 바로 넘어 올 수 있다.

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('pipeline-1',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer()),
                                                                                         ('minmaxscaler',
                                                                                          MinMaxScaler())]),
                                                                         ['Oxid_time',
                                                                          'thickness',
                                                                          'resist_target',
                                                                          'Line_CD',
                                                                          'Etching_rate']),
                                                                        ('pipeline-2',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehotencoder',
                                                                                          OneHotEncoder())]),
                                                                         ['Vapor',
                                                                          'UV_type'])])),
                                       ('linearregression',
                                        LinearRegression())]),
             param_grid={})

In [41]:
# 교차검증 이후 가장 성능이 좋은 Model 선택
best_model = grid_model.best_estimator_

In [42]:
evaluation_reg(best_model)

학습 데이터 결정계수 :  0.38311464373728366
검증 데이터 결정계수 :  0.28547901254699726
학습 데이터 MSE:  2531.901336696589
검증 데이터 MSE:  2114.6014924525657
학습 데이터 MAE:  36.33614506435797
검증 데이터 MAE:  35.58755076958039

**Hyper Parameter Tuning**

In [44]:
# 의사결정나무 알고리즘 
from sklearn.tree import DecisionTreeRegressor

In [45]:
# 연속형과 범주형을 나누어 처리하는 pipe를 구성 
preprocessing_pipe = make_column_transformer( (numeric_pipe, numeric_list), (category_pipe, category_list) )
pipe_model = make_pipeline(preprocessing_pipe, DecisionTreeRegressor() )

In [46]:
pipe_model

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer()),
                                                                  ('minmaxscaler',
                                                                   MinMaxScaler())]),
                                                  ['Oxid_time', 'thickness',
                                                   'resist_target', 'Line_CD',
                                                   'Etching_rate']),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder())]),
                                                  ['Vapor', 'UV_type'])])),
                ('decisiontreeregressor', DecisionTreeRegressor())])

In [49]:
# depth : 5~10 5개 / split : 1~10 10개 / leaf : 5~10 5개 -> 250가지 경우의 수 
hyperparameter = {'decisiontreeregressor__max_depth' : range(5,11), 'decisiontreeregressor__min_samples_split': range(1,11),
                  'decisiontreeregressor__min_samples_leaf': range(5,11)}

grid_model = GridSearchCV(pipe_model, param_grid=hyperparameter, cv=5)
# 5회의 교차검증 수행
grid_model.fit(X_train, Y_train)

E:\aaan\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
180 fits failed out of a total of 1800.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
180 fits failed with the following error:
Traceback (most recent call last):
  File "E:\aaan\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "E:\aaan\Lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\aaan\Lib\site-packages\sklearn\pipeline.py", line 420, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "E:\aaan\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "E:\aaan\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "E:\aaan\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeRegressor must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
E:\aaan\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan 0.28114358 0.28114358 0.28114358 0.28114358 0.28114358
 0.28114358 0.28114358 0.28114358 0.28114358        nan 0.26927114
 0.26927114 0.26927114 0.26927114 0.26927114 0.26927114 0.26927114
 0.26927114 0.26927114        nan 0.26446005 0.26446005 0.26446005
 0.26446005 0.26446005 0.26446005 0.26446005 0.26446005 0.26446005
        nan 0.25964486 0.25964486 0.25964486 0.25964486 0.25964486
 0.25964486 0.25964486 0.25964486 0.25964486        nan 0.25584335
 0.25584335 0.25584335 0.25584335 0.25584335 0.25584335 0.25584335
 0.25584335 0.25584335        nan 0.26299308 0.26299308 0.26299308
 0.26299308 0.26299308 0.26299308 0.26299308 0.26299308 0.26299308
        nan 0.25375979 0.25375979 0.25375979 0.25375979 0.25375979
 0.25375979 0.25375979 0.25375979 0.25375979        nan 0.24785455
 0.24785455 0.24785455 0.24785455 0.24785455 0.24785455 0.24785455
 0.24785455 0.24785455        nan 0.23865649 0.23865649 0.23865649
 0.23922094 0.23649176 0.23705621 0.23649176 0.23922094 0.23865649
        nan 0.24454944 0.2451139  0.2451139  0.24454944 0.24454944
 0.24454944 0.24454944 0.2451139  0.24454944        nan 0.25155328
 0.25098883 0.25098883 0.25155328 0.25098883 0.25155328 0.25155328
 0.25155328 0.25098883        nan 0.24997282 0.24997282 0.24940837
 0.24940837 0.24997282 0.24940837 0.24940837 0.24940837 0.24940837
        nan 0.2214879  0.2214879  0.2214879  0.21704038 0.21704038
 0.2214879  0.21704038 0.2214879  0.21704038        nan 0.21113122
 0.21113122 0.2066837  0.21113122 0.2066837  0.21113122 0.21113122
 0.2066837  0.2066837         nan 0.21884241 0.21890388 0.21816214
 0.21747937 0.21690355 0.21622078 0.21890388 0.21690355 0.21822361
        nan 0.22343093 0.22409232 0.22343093 0.22409232 0.22409232
 0.22343093 0.22409232 0.22409232 0.22409232        nan 0.22991776
 0.22928576 0.22928576 0.22928576 0.22928576 0.22991776 0.22928576
 0.22928576 0.22928576        nan 0.22432515 0.22432515 0.22369315
 0.22369315 0.22432515 0.22432515 0.22432515 0.22432515 0.22432515
        nan 0.17386256 0.16620289 0.17386256 0.16620289 0.17065041
 0.17065041 0.16620289 0.16941503 0.17065041        nan 0.18925457
 0.18925457 0.18480704 0.18480704 0.18480704 0.18480704 0.18925457
 0.18925457 0.18480704        nan 0.20885711 0.20741795 0.20809821
 0.20891858 0.20817684 0.20823831 0.20823831 0.20809821 0.20891858
        nan 0.22648767 0.22648767 0.22650016 0.22648767 0.22648767
 0.22648767 0.22650016 0.22648767 0.22648767        nan 0.23671078
 0.23607878 0.23607878 0.23607878 0.23671078 0.23671078 0.23671078
 0.23607878 0.23607878        nan 0.22059564 0.22059564 0.22122764
 0.22122764 0.22122764 0.22122764 0.22122764 0.22122764 0.22122764
        nan 0.15657804 0.15657804 0.15979019 0.15657804 0.15213052
 0.15979019 0.15979019 0.15657804 0.15213052        nan 0.17744947
 0.18189699 0.18189699 0.17744947 0.18189699 0.17744947 0.17744947
 0.18189699 0.17744947        nan 0.20418527 0.20154899 0.20274611
 0.20274611 0.20342637 0.203505   0.20230789 0.20154899 0.20148752
        nan 0.22264023 0.22265272 0.22264023 0.22264023 0.22265272
 0.22265272 0.22264023 0.22264023 0.22264023        nan 0.24107158
 0.24043958 0.24107158 0.24107158 0.24107158 0.24043958 0.24107158
 0.24107158 0.24043958        nan 0.22296343 0.22296343 0.22233143
 0.22233143 0.22296343 0.22233143 0.22233143 0.22296343 0.22233143
        nan 0.14333797 0.14343628 0.1478838  0.14655012 0.14664842
 0.14343628 0.15099764 0.14333797 0.1478838         nan 0.17688013
 0.1724326  0.17688013 0.1724326  0.1724326  0.17688013 0.1724326
 0.1724326  0.1724326         nan 0.19475406 0.19669292 0.19601265
 0.19481554 0.19751329 0.19745181 0.19481554 0.19475406 0.19551296
        nan 0.21730497 0.21729247 0.21730497 0.21730497 0.21729247
 0.21729247 0.21730497 0.21729247 0.21729247        nan 0.23851424
 0.23788224 0.23788224 0.23851424 0.23851424 0.23851424 0.23788224
 0.23851424 0.23788224        nan 0.22231953 0.22231953 0.22231953
 0.22168753 0.22168753 0.22168753 0.22168753 0.22168753 0.22231953]
  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('pipeline-1',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer()),
                                                                                         ('minmaxscaler',
                                                                                          MinMaxScaler())]),
                                                                         ['Oxid_time',
                                                                          'thickness',
                                                                          'resist_target',
                                                                          'Line_CD',
                                                                          'Etching_rate']),
                                                                        ('pipeline-2',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehotencoder',
                                                                                          OneHotEncoder())]),
                                                                         ['Vapor',
                                                                          'UV_type'])])),
                                       ('decisiontreeregressor',
                                        DecisionTreeRegressor())]),
             param_grid={'decisiontreeregressor__max_depth': range(5, 11),
                         'decisiontreeregressor__min_samples_leaf': range(5, 11),
                         'decisiontreeregressor__min_samples_split': range(1, 11)})

In [50]:
# 가장 적절한 모델을 선택
best_model= grid_model.best_estimator_
best_model

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer()),
                                                                  ('minmaxscaler',
                                                                   MinMaxScaler())]),
                                                  ['Oxid_time', 'thickness',
                                                   'resist_target', 'Line_CD',
                                                   'Etching_rate']),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder())]),
                                                  ['Vapor', 'UV_type'])])),
                ('decisiontreeregressor',
                 DecisionTreeRegressor(max_depth=5, min_samples_leaf=5))])

In [51]:
evaluation_reg(best_model)

학습 데이터 결정계수 :  0.6071143811638606
검증 데이터 결정계수 :  -0.14097311763387732
학습 데이터 MSE:  1612.532399093697
검증 데이터 MSE:  3376.6726237072885
학습 데이터 MAE:  30.07200540661487
검증 데이터 MAE:  40.95643622461593